# The version of docker compose to use
version: '3.4'

volumes:
    dockerize_opt:
        external:
            name: dockerize_opt
    dockerize_ssh:
        external:
            name: dockerize_ssh

x-dockerize-common:
    common:
        &dockerize-common
        image: {image_name}:latest
        privileged: true
        volumes:
           - dockerize_opt:/opt:delegated
           - dockerize_ssh:/root/.ssh:delegated
           - ~:/host:delegated
           - .:/project:delegated
services:
    shell:
        <<: *dockerize-common
        command: /bin/bash
        ports:
            - "5555:5555"
            - "8000:8000"
            - "8888:8888"


    notebook:
        <<: *dockerize-common
        command: bash -c 'source ~/.bashrc && jupyter notebook --allow-root --ip 0.0.0.0 --port 9999 --NotebookApp.iopub_data_rate_limit=10000000000'
        ports:
            - "9999:9999"
